### ISSUE TITLE
Чем бы образы дизассемблировать?

### ISSUE THREAD

**Issue by AndrewSav** [nzeemin/bkbtl-doc#1]
А чем можно дизассемблровать образы, для которых нету исходников? (Те которые есть, тоже, я подозреваю чем то были дизассемблированы. Чем?)

**Comment by nzeemin** [comment]
Я использую дизассемблер встроенный в эмулятор -- переходим в Debug-режим и в консоли выполняем команду d либо D.
Также в RT-11 есть команда DESS.

**Comment by AndrewSav** [comment]
Спасибо.
